version: "3"

services:
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    restart: "always"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: simple-bank-db
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
